version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

volumes:
  postgres_data:

networks:
  nestjs-network:
